batch_size: 8
betas:
- 0.5
- 0.999
checkpoint_dir: ./checkpoints
data_root: ./data
load_checkpoint: False
device: cuda
image_size:
- 256
- 192
lambda_i:
- 0.03125
- 0.0625
- 0.125
- 0.25
- 1.0
layer_idx:
- 2
- 7
- 12
- 21
- 30
learning_rate: 0.0002
log_interval: 10
num_epochs: 16
num_workers: 2
tensorboard_dir: ./tensorboard
training_steps: 1500.0
